# Generated by Django 3.2.7 on 2021-10-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20210929_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmodel',
            name='sns_image',
        ),
    ]
